/* A Bison parser, made by GNU Bison 3.0.4.  */

/* Bison implementation for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* C LALR(1) parser skeleton written by Richard Stallman, by
   simplifying the original so-called "semantic" parser.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

/* Identify Bison output.  */
#define YYBISON 1

/* Bison version.  */
#define YYBISON_VERSION "3.0.4"

/* Skeleton name.  */
#define YYSKELETON_NAME "yacc.c"

/* Pure parsers.  */
#define YYPURE 2

/* Push parsers.  */
#define YYPUSH 0

/* Pull parsers.  */
#define YYPULL 1

/* Substitute the type names.  */
#define YYSTYPE         Q_PARSER_STYPE
/* Substitute the variable and function names.  */
#define yyparse         q_parser_parse
#define yylex           q_parser_lex
#define yyerror         q_parser_error
#define yydebug         q_parser_debug
#define yynerrs         q_parser_nerrs


/* Copy the first part of user declarations.  */
#line 1 "./src/database/database/code/q_parser.y" /* yacc.c:339  */

#include "os_stdlib.h"
#include "os_errno.h"
#include "c_base.h"
#include "c_collection.h"
#include "q_expr.h"
#include "q_helper.h"

#include "os_report.h"
#include "vortex_os.h"

/* yyscan_t is an opaque pointer, a typedef is required here to break a
   circular dependency introduced with bison 2.6 (normally a typedef is
   generated by flex). the define is required to disable the typedef in flex
   generated code */
#define YY_TYPEDEF_YY_SCANNER_T

typedef void *yyscan_t;

struct q_context {
    int line;
    int column;
    q_expr expr;
};


int
yyerror(
    yyscan_t yyscanner, struct q_context *context, char *text);

void
dollar_warning(
    void);

#line 108 "./src/database/database/code/q_parser.c" /* yacc.c:339  */

# ifndef YY_NULLPTR
#  if defined __cplusplus && 201103L <= __cplusplus
#   define YY_NULLPTR nullptr
#  else
#   define YY_NULLPTR 0
#  endif
# endif

/* Enabling verbose error messages.  */
#ifdef YYERROR_VERBOSE
# undef YYERROR_VERBOSE
# define YYERROR_VERBOSE 1
#else
# define YYERROR_VERBOSE 0
#endif


/* Debug traces.  */
#ifndef Q_PARSER_DEBUG
# if defined YYDEBUG
#if YYDEBUG
#   define Q_PARSER_DEBUG 1
#  else
#   define Q_PARSER_DEBUG 0
#  endif
# else /* ! defined YYDEBUG */
#  define Q_PARSER_DEBUG 0
# endif /* ! defined YYDEBUG */
#endif  /* ! defined Q_PARSER_DEBUG */
#if Q_PARSER_DEBUG
extern int q_parser_debug;
#endif

/* Token type.  */
#ifndef Q_PARSER_TOKENTYPE
# define Q_PARSER_TOKENTYPE
  enum q_parser_tokentype
  {
    DEFINE = 258,
    AS_KEYWORD = 259,
    NIL = 260,
    TRUET = 261,
    FALSET = 262,
    LRPAR = 263,
    RRPAR = 264,
    MUL = 265,
    LIKE = 266,
    BETWEEN = 267,
    EQUAL = 268,
    NOTEQUAL = 269,
    GREATER = 270,
    LESS = 271,
    GREATEREQUAL = 272,
    LESSEQUAL = 273,
    NOT = 274,
    AND = 275,
    OR = 276,
    REF = 277,
    DOT = 278,
    ALL = 279,
    SELECT = 280,
    UNDEFINED = 281,
    FROM = 282,
    WHERE = 283,
    COLON = 284,
    COMMA = 285,
    DOUBLECOLON = 286,
    DOLLAR = 287,
    PERCENT = 288,
    SELECT_DISTINCT = 289,
    JOIN = 290,
    identifier = 291,
    stringLiteral = 292,
    queryId = 293,
    charLiteral = 294,
    longlongLiteral = 295,
    ulonglongLiteral = 296,
    doubleLiteral = 297
  };
#endif

/* Value type.  */
#if ! defined Q_PARSER_STYPE && ! defined Q_PARSER_STYPE_IS_DECLARED

union Q_PARSER_STYPE
{
#line 36 "./src/database/database/code/q_parser.y" /* yacc.c:355  */

    c_char *    String;
    c_char      Char;
    c_longlong  Integer;
    c_ulonglong UInteger;
    c_double    Float;
    c_type      Type;
    q_list      List;
    q_expr      Expr;
    q_tag       Tag;

#line 208 "./src/database/database/code/q_parser.c" /* yacc.c:355  */
};

typedef union Q_PARSER_STYPE Q_PARSER_STYPE;
# define Q_PARSER_STYPE_IS_TRIVIAL 1
# define Q_PARSER_STYPE_IS_DECLARED 1
#endif



int q_parser_parse (yyscan_t scanner, struct q_context *context);



/* Copy the second part of user declarations.  */
#line 48 "./src/database/database/code/q_parser.y" /* yacc.c:358  */

/* q_parser_lex must be declared here because q_parser_lex (yylex if no prefix
   would be specified) signature is augmented with an extra argument */
int q_parser_lex(
    YYSTYPE * yylval_param, yyscan_t yyscanner, struct q_context *context);

#define YY_DECL int q_parser_lex \
    (YYSTYPE * yylval_param, yyscan_t yyscanner, struct q_context *context)

#line 233 "./src/database/database/code/q_parser.c" /* yacc.c:358  */

#ifdef short
# undef short
#endif

#ifdef YYTYPE_UINT8
typedef YYTYPE_UINT8 yytype_uint8;
#else
typedef unsigned char yytype_uint8;
#endif

#ifdef YYTYPE_INT8
typedef YYTYPE_INT8 yytype_int8;
#else
typedef signed char yytype_int8;
#endif

#ifdef YYTYPE_UINT16
typedef YYTYPE_UINT16 yytype_uint16;
#else
typedef unsigned short int yytype_uint16;
#endif

#ifdef YYTYPE_INT16
typedef YYTYPE_INT16 yytype_int16;
#else
typedef short int yytype_int16;
#endif

#ifndef YYSIZE_T
# ifdef __SIZE_TYPE__
#  define YYSIZE_T __SIZE_TYPE__
# elif defined size_t
#  define YYSIZE_T size_t
# elif ! defined YYSIZE_T
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# else
#  define YYSIZE_T unsigned int
# endif
#endif

#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)

#ifndef YY_
# if defined YYENABLE_NLS && YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> /* INFRINGES ON USER NAME SPACE */
#   define YY_(Msgid) dgettext ("bison-runtime", Msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(Msgid) Msgid
# endif
#endif

#ifndef YY_ATTRIBUTE
# if (defined __GNUC__                                               \
      && (2 < __GNUC__ || (__GNUC__ == 2 && 96 <= __GNUC_MINOR__)))  \
     || defined __SUNPRO_C && 0x5110 <= __SUNPRO_C
#  define YY_ATTRIBUTE(Spec) __attribute__(Spec)
# else
#  define YY_ATTRIBUTE(Spec) /* empty */
# endif
#endif

#ifndef YY_ATTRIBUTE_PURE
# define YY_ATTRIBUTE_PURE   YY_ATTRIBUTE ((__pure__))
#endif

#ifndef YY_ATTRIBUTE_UNUSED
# define YY_ATTRIBUTE_UNUSED YY_ATTRIBUTE ((__unused__))
#endif

#if !defined _Noreturn \
     && (!defined __STDC_VERSION__ || __STDC_VERSION__ < 201112)
# if defined _MSC_VER && 1200 <= _MSC_VER
#  define _Noreturn __declspec (noreturn)
# else
#  define _Noreturn YY_ATTRIBUTE ((__noreturn__))
# endif
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YYUSE(E) ((void) (E))
#else
# define YYUSE(E) /* empty */
#endif

#if defined __GNUC__ && 407 <= __GNUC__ * 100 + __GNUC_MINOR__
/* Suppress an incorrect diagnostic about yylval being uninitialized.  */
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN \
    _Pragma ("GCC diagnostic push") \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")\
    _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
# define YY_IGNORE_MAYBE_UNINITIALIZED_END \
    _Pragma ("GCC diagnostic pop")
#else
# define YY_INITIAL_VALUE(Value) Value
#endif
#ifndef YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_END
#endif
#ifndef YY_INITIAL_VALUE
# define YY_INITIAL_VALUE(Value) /* Nothing. */
#endif


#if ! defined yyoverflow || YYERROR_VERBOSE

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# ifdef YYSTACK_USE_ALLOCA
#  if YYSTACK_USE_ALLOCA
#   ifdef __GNUC__
#    define YYSTACK_ALLOC __builtin_alloca
#   elif defined __BUILTIN_VA_ARG_INCR
#    include <alloca.h> /* INFRINGES ON USER NAME SPACE */
#   elif defined _AIX
#    define YYSTACK_ALLOC __alloca
#   elif defined _MSC_VER
#    include <malloc.h> /* INFRINGES ON USER NAME SPACE */
#    define alloca _alloca
#   else
#    define YYSTACK_ALLOC alloca
#    if ! defined _ALLOCA_H && ! defined EXIT_SUCCESS
#     include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
      /* Use EXIT_SUCCESS as a witness for stdlib.h.  */
#     ifndef EXIT_SUCCESS
#      define EXIT_SUCCESS 0
#     endif
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's 'empty if-body' warning.  */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (0)
#  ifndef YYSTACK_ALLOC_MAXIMUM
    /* The OS might guarantee only one guard page at the bottom of the stack,
       and a page size can be as small as 4096 bytes.  So we cannot safely
       invoke alloca (N) if N exceeds 4096.  Use a slightly smaller number
       to allow for a few compiler-allocated temporary stack slots.  */
#   define YYSTACK_ALLOC_MAXIMUM 4032 /* reasonable circa 2006 */
#  endif
# else
#  define YYSTACK_ALLOC YYMALLOC
#  define YYSTACK_FREE YYFREE
#  ifndef YYSTACK_ALLOC_MAXIMUM
#   define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#  endif
#  if (defined __cplusplus && ! defined EXIT_SUCCESS \
       && ! ((defined YYMALLOC || defined malloc) \
             && (defined YYFREE || defined free)))
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   ifndef EXIT_SUCCESS
#    define EXIT_SUCCESS 0
#   endif
#  endif
#  ifndef YYMALLOC
#   define YYMALLOC malloc
#   if ! defined malloc && ! defined EXIT_SUCCESS
void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
#  ifndef YYFREE
#   define YYFREE free
#   if ! defined free && ! defined EXIT_SUCCESS
void free (void *); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
# endif
#endif /* ! defined yyoverflow || YYERROR_VERBOSE */


#if (! defined yyoverflow \
     && (! defined __cplusplus \
         || (defined Q_PARSER_STYPE_IS_TRIVIAL && Q_PARSER_STYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  yytype_int16 yyss_alloc;
  YYSTYPE yyvs_alloc;
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# define YYSTACK_BYTES(N) \
     ((N) * (sizeof (yytype_int16) + sizeof (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)

# define YYCOPY_NEEDED 1

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack_alloc, Stack)                           \
    do                                                                  \
      {                                                                 \
        YYSIZE_T yynewbytes;                                            \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / sizeof (*yyptr);                          \
      }                                                                 \
    while (0)

#endif

#if defined YYCOPY_NEEDED && YYCOPY_NEEDED
/* Copy COUNT objects from SRC to DST.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if defined __GNUC__ && 1 < __GNUC__
#   define YYCOPY(Dst, Src, Count) \
      __builtin_memcpy (Dst, Src, (Count) * sizeof (*(Src)))
#  else
#   define YYCOPY(Dst, Src, Count)              \
      do                                        \
        {                                       \
          YYSIZE_T yyi;                         \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
#  endif
# endif
#endif /* !YYCOPY_NEEDED */

/* YYFINAL -- State number of the termination state.  */
#define YYFINAL  45
/* YYLAST -- Last index in YYTABLE.  */
#define YYLAST   204

/* YYNTOKENS -- Number of terminals.  */
#define YYNTOKENS  43
/* YYNNTS -- Number of nonterminals.  */
#define YYNNTS  25
/* YYNRULES -- Number of rules.  */
#define YYNRULES  66
/* YYNSTATES -- Number of states.  */
#define YYNSTATES  104

/* YYTRANSLATE[YYX] -- Symbol number corresponding to YYX as returned
   by yylex, with out-of-bounds checking.  */
#define YYUNDEFTOK  2
#define YYMAXUTOK   297

#define YYTRANSLATE(YYX)                                                \
  ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)

/* YYTRANSLATE[TOKEN-NUM] -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex, without out-of-bounds checking.  */
static const yytype_uint8 yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    19,    20,    21,    22,    23,    24,
      25,    26,    27,    28,    29,    30,    31,    32,    33,    34,
      35,    36,    37,    38,    39,    40,    41,    42
};

#if Q_PARSER_DEBUG
  /* YYRLINE[YYN] -- Source line where rule number YYN was defined.  */
static const yytype_uint16 yyrline[] =
{
       0,   117,   117,   118,   123,   125,   136,   138,   143,   145,
     147,   149,   154,   159,   161,   166,   168,   170,   181,   186,
     188,   199,   200,   211,   226,   228,   241,   243,   248,   250,
     261,   263,   265,   267,   272,   274,   276,   278,   283,   285,
     287,   289,   294,   296,   301,   302,   306,   316,   323,   330,
     340,   342,   347,   349,   351,   353,   358,   360,   362,   364,
     366,   373,   377,   379,   381,   383,   385
};
#endif

#if Q_PARSER_DEBUG || YYERROR_VERBOSE || 0
/* YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
   First, the terminals, then, starting at YYNTOKENS, nonterminals.  */
static const char *const yytname[] =
{
  "$end", "error", "$undefined", "DEFINE", "AS_KEYWORD", "NIL", "TRUET",
  "FALSET", "LRPAR", "RRPAR", "MUL", "LIKE", "BETWEEN", "EQUAL",
  "NOTEQUAL", "GREATER", "LESS", "GREATEREQUAL", "LESSEQUAL", "NOT", "AND",
  "OR", "REF", "DOT", "ALL", "SELECT", "UNDEFINED", "FROM", "WHERE",
  "COLON", "COMMA", "DOUBLECOLON", "DOLLAR", "PERCENT", "SELECT_DISTINCT",
  "JOIN", "identifier", "stringLiteral", "queryId", "charLiteral",
  "longlongLiteral", "ulonglongLiteral", "doubleLiteral", "$accept",
  "program", "query", "selectExpr", "projectionAttributes",
  "objectConstruction", "fieldList", "field", "fromClause", "joinExpr",
  "whereClauseOpt", "expr", "orExpr", "andExpr", "notExpr", "equalityExpr",
  "relationalExpr", "postfixExpr", "propertyList", "propertyOper", "ID",
  "scopedName", "equalityOper", "relationalOper", "literal", YY_NULLPTR
};
#endif

# ifdef YYPRINT
/* YYTOKNUM[NUM] -- (External) token number corresponding to the
   (internal) symbol number NUM (which must be that of a token).  */
static const yytype_uint16 yytoknum[] =
{
       0,   256,   257,   258,   259,   260,   261,   262,   263,   264,
     265,   266,   267,   268,   269,   270,   271,   272,   273,   274,
     275,   276,   277,   278,   279,   280,   281,   282,   283,   284,
     285,   286,   287,   288,   289,   290,   291,   292,   293,   294,
     295,   296,   297
};
# endif

#define YYPACT_NINF -40

#define yypact_value_is_default(Yystate) \
  (!!((Yystate) == (-40)))

#define YYTABLE_NINF -48

#define yytable_value_is_error(Yytable_value) \
  0

  /* YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
     STATE-NUM.  */
static const yytype_int16 yypact[] =
{
      68,   -40,   -40,   -40,   106,   106,   123,   -40,   -30,   -26,
     -24,   123,    -5,   -40,   -40,   -40,   -40,   -40,    20,   -40,
     -40,   -40,   -40,    12,     5,   -40,   -40,    23,    -1,    -8,
     -40,    15,   -40,   -40,    22,   -40,    21,   -40,    -2,     7,
       4,   -40,   -40,   -40,    22,   -40,   106,   106,   145,   -40,
     -40,   -40,   -40,   -40,   -40,   145,   162,   162,    38,   -40,
     -40,     7,    16,    17,   -40,    16,    26,   162,   162,   162,
     162,    26,   -40,   -40,   -40,   -40,   -40,    27,    37,   162,
      16,   -40,   -40,   -40,   -40,    25,   106,   -40,   -40,     3,
     -40,   -40,     1,   -40,   162,    41,   -40,    16,   -40,   -40,
     -40,   162,   -40,   -40
};

  /* YYDEFACT[STATE-NUM] -- Default reduction number in state STATE-NUM.
     Performed when YYTABLE does not specify something else to do.  Zero
     means the default is an error.  */
static const yytype_uint8 yydefact[] =
{
       2,    65,    63,    64,     0,     0,     0,    66,     0,     0,
       0,     0,    46,    60,    59,    56,    57,    58,     0,     3,
       4,     5,    23,    24,    26,    28,    30,    34,    38,    41,
      40,     0,    29,     8,     0,    11,    10,    13,     9,    38,
      41,    48,    61,    62,     0,     1,     0,     0,     0,    50,
      51,    54,    52,    55,    53,     0,     0,     0,     0,    45,
      44,    39,     0,     0,    33,     0,    21,     0,     0,     0,
       0,    21,    25,    27,    32,    31,    35,    34,     0,     0,
       0,    46,    42,    49,    18,    19,     0,     6,    14,    17,
      16,    15,     0,     7,     0,     0,    43,     0,    22,    12,
      36,     0,    20,    37
};

  /* YYPGOTO[NTERM-NUM].  */
static const yytype_int8 yypgoto[] =
{
     -40,   -40,   -40,   -40,    52,   -40,    -6,    10,    24,   -31,
      -4,    -3,    32,    35,    74,   -39,    28,     2,   -40,    29,
       0,     8,   -40,   -40,   -40
};

  /* YYDEFGOTO[NTERM-NUM].  */
static const yytype_int8 yydefgoto[] =
{
      -1,    18,    19,    20,    34,    35,    36,    37,    66,    84,
      87,    21,    22,    23,    24,    25,    26,    27,    61,    62,
      39,    29,    55,    56,    30
};

  /* YYTABLE[YYPACT[STATE-NUM]] -- What to do in state STATE-NUM.  If
     positive, shift that token.  If negative, reduce the rule whose
     number is the opposite.  If YYTABLE_NINF, syntax error.  */
static const yytype_int8 yytable[] =
{
      28,    31,    68,   -47,    28,    28,    41,    68,    38,    74,
      99,    57,    70,    38,    40,    42,    75,    43,    58,    40,
      45,    59,    60,    63,    64,    47,   -47,    69,   -17,    59,
      60,    67,    69,    46,    48,    63,    49,    50,    51,    52,
      53,    54,    51,    52,    53,    54,    28,    28,    28,    65,
      79,    67,    81,    83,    86,    28,    28,    94,    77,    78,
      97,   101,    82,    44,    92,    85,   102,    93,    71,    89,
      90,    91,    89,     1,     2,     3,     4,    88,    72,    32,
      96,    95,    73,    98,    76,     0,    28,     5,     0,     0,
      80,     0,     0,     6,     7,     0,   100,    85,     0,     8,
       9,    10,    11,   103,    12,    13,     0,    14,    15,    16,
      17,     1,     2,     3,     4,     0,     0,     0,     0,     0,
       0,     0,     0,     0,     0,     5,     0,     0,     1,     2,
       3,     0,     7,    33,     0,     0,     0,     8,     9,    10,
       0,     0,    12,    13,     0,    14,    15,    16,    17,     7,
       1,     2,     3,     4,     8,     9,    10,     0,     0,    12,
      13,     0,    14,    15,    16,    17,     0,     1,     2,     3,
       0,     7,     0,     0,     0,     0,     8,     9,    10,     0,
       0,    12,    13,     0,    14,    15,    16,    17,     7,     0,
       0,     0,     0,     8,     9,    10,     0,     0,    12,    13,
       0,    14,    15,    16,    17
};

static const yytype_int8 yycheck[] =
{
       0,     4,     4,     8,     4,     5,    36,     4,     6,    48,
       9,    12,     8,    11,     6,    41,    55,    41,    19,    11,
       0,    22,    23,    31,     9,    20,    31,    29,    30,    22,
      23,    30,    29,    21,    11,    31,    13,    14,    15,    16,
      17,    18,    15,    16,    17,    18,    46,    47,    48,    27,
      12,    30,    36,    36,    28,    55,    56,    20,    56,    57,
      35,    20,    62,    11,    70,    65,    97,    71,    44,    67,
      68,    69,    70,     5,     6,     7,     8,    67,    46,     5,
      80,    79,    47,    86,    56,    -1,    86,    19,    -1,    -1,
      61,    -1,    -1,    25,    26,    -1,    94,    97,    -1,    31,
      32,    33,    34,   101,    36,    37,    -1,    39,    40,    41,
      42,     5,     6,     7,     8,    -1,    -1,    -1,    -1,    -1,
      -1,    -1,    -1,    -1,    -1,    19,    -1,    -1,     5,     6,
       7,    -1,    26,    10,    -1,    -1,    -1,    31,    32,    33,
      -1,    -1,    36,    37,    -1,    39,    40,    41,    42,    26,
       5,     6,     7,     8,    31,    32,    33,    -1,    -1,    36,
      37,    -1,    39,    40,    41,    42,    -1,     5,     6,     7,
      -1,    26,    -1,    -1,    -1,    -1,    31,    32,    33,    -1,
      -1,    36,    37,    -1,    39,    40,    41,    42,    26,    -1,
      -1,    -1,    -1,    31,    32,    33,    -1,    -1,    36,    37,
      -1,    39,    40,    41,    42
};

  /* YYSTOS[STATE-NUM] -- The (internal number of the) accessing
     symbol of state STATE-NUM.  */
static const yytype_uint8 yystos[] =
{
       0,     5,     6,     7,     8,    19,    25,    26,    31,    32,
      33,    34,    36,    37,    39,    40,    41,    42,    44,    45,
      46,    54,    55,    56,    57,    58,    59,    60,    63,    64,
      67,    54,    57,    10,    47,    48,    49,    50,    60,    63,
      64,    36,    41,    41,    47,     0,    21,    20,    11,    13,
      14,    15,    16,    17,    18,    65,    66,    12,    19,    22,
      23,    61,    62,    31,     9,    27,    51,    30,     4,    29,
       8,    51,    55,    56,    58,    58,    59,    60,    60,    12,
      62,    36,    63,    36,    52,    63,    28,    53,    50,    60,
      60,    60,    49,    53,    20,    60,    63,    35,    54,     9,
      60,    20,    52,    60
};

  /* YYR1[YYN] -- Symbol number of symbol that rule YYN derives.  */
static const yytype_uint8 yyr1[] =
{
       0,    43,    44,    44,    45,    45,    46,    46,    47,    47,
      47,    47,    48,    49,    49,    50,    50,    50,    51,    52,
      52,    53,    53,    54,    55,    55,    56,    56,    57,    57,
      58,    58,    58,    58,    59,    59,    59,    59,    60,    60,
      60,    60,    61,    61,    62,    62,    63,    64,    64,    64,
      65,    65,    66,    66,    66,    66,    67,    67,    67,    67,
      67,    67,    67,    67,    67,    67,    67
};

  /* YYR2[YYN] -- Number of symbols on the right hand side of rule YYN.  */
static const yytype_uint8 yyr2[] =
{
       0,     2,     0,     1,     1,     1,     4,     4,     1,     1,
       1,     1,     4,     1,     3,     3,     3,     1,     2,     1,
       3,     0,     2,     1,     1,     3,     1,     3,     1,     2,
       1,     3,     3,     3,     1,     3,     5,     6,     1,     2,
       1,     1,     2,     3,     1,     1,     1,     1,     2,     3,
       1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
       1,     2,     2,     1,     1,     1,     1
};


#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (yychar = YYEMPTY)
#define YYEMPTY         (-2)
#define YYEOF           0

#define YYACCEPT        goto yyacceptlab
#define YYABORT         goto yyabortlab
#define YYERROR         goto yyerrorlab


#define YYRECOVERING()  (!!yyerrstatus)

#define YYBACKUP(Token, Value)                                  \
do                                                              \
  if (yychar == YYEMPTY)                                        \
    {                                                           \
      yychar = (Token);                                         \
      yylval = (Value);                                         \
      YYPOPSTACK (yylen);                                       \
      yystate = *yyssp;                                         \
      goto yybackup;                                            \
    }                                                           \
  else                                                          \
    {                                                           \
      yyerror (scanner, context, YY_("syntax error: cannot back up")); \
      YYERROR;                                                  \
    }                                                           \
while (0)

/* Error token number */
#define YYTERROR        1
#define YYERRCODE       256



/* Enable debugging if requested.  */
#if Q_PARSER_DEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)                        \
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (0)

/* This macro is provided for backward compatibility. */
#ifndef YY_LOCATION_PRINT
# define YY_LOCATION_PRINT(File, Loc) ((void) 0)
#endif


# define YY_SYMBOL_PRINT(Title, Type, Value, Location)                    \
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Type, Value, scanner, context); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (0)


/*----------------------------------------.
| Print this symbol's value on YYOUTPUT.  |
`----------------------------------------*/

static void
yy_symbol_value_print (FILE *yyoutput, int yytype, YYSTYPE const * const yyvaluep, yyscan_t scanner, struct q_context *context)
{
  FILE *yyo = yyoutput;
  YYUSE (yyo);
  YYUSE (scanner);
  YYUSE (context);
  if (!yyvaluep)
    return;
# ifdef YYPRINT
  if (yytype < YYNTOKENS)
    YYPRINT (yyoutput, yytoknum[yytype], *yyvaluep);
# endif
  YYUSE (yytype);
}


/*--------------------------------.
| Print this symbol on YYOUTPUT.  |
`--------------------------------*/

static void
yy_symbol_print (FILE *yyoutput, int yytype, YYSTYPE const * const yyvaluep, yyscan_t scanner, struct q_context *context)
{
  YYFPRINTF (yyoutput, "%s %s (",
             yytype < YYNTOKENS ? "token" : "nterm", yytname[yytype]);

  yy_symbol_value_print (yyoutput, yytype, yyvaluep, scanner, context);
  YYFPRINTF (yyoutput, ")");
}

/*------------------------------------------------------------------.
| yy_stack_print -- Print the state stack from its BOTTOM up to its |
| TOP (included).                                                   |
`------------------------------------------------------------------*/

static void
yy_stack_print (yytype_int16 *yybottom, yytype_int16 *yytop)
{
  YYFPRINTF (stderr, "Stack now");
  for (; yybottom <= yytop; yybottom++)
    {
      int yybot = *yybottom;
      YYFPRINTF (stderr, " %d", yybot);
    }
  YYFPRINTF (stderr, "\n");
}

# define YY_STACK_PRINT(Bottom, Top)                            \
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (0)


/*------------------------------------------------.
| Report that the YYRULE is going to be reduced.  |
`------------------------------------------------*/

static void
yy_reduce_print (yytype_int16 *yyssp, YYSTYPE *yyvsp, int yyrule, yyscan_t scanner, struct q_context *context)
{
  unsigned long int yylno = yyrline[yyrule];
  int yynrhs = yyr2[yyrule];
  int yyi;
  YYFPRINTF (stderr, "Reducing stack by rule %d (line %lu):\n",
             yyrule - 1, yylno);
  /* The symbols being reduced.  */
  for (yyi = 0; yyi < yynrhs; yyi++)
    {
      YYFPRINTF (stderr, "   $%d = ", yyi + 1);
      yy_symbol_print (stderr,
                       yystos[yyssp[yyi + 1 - yynrhs]],
                       &(yyvsp[(yyi + 1) - (yynrhs)])
                                              , scanner, context);
      YYFPRINTF (stderr, "\n");
    }
}

# define YY_REDUCE_PRINT(Rule)          \
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyssp, yyvsp, Rule, scanner, context); \
} while (0)

/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !Q_PARSER_DEBUG */
# define YYDPRINTF(Args)
# define YY_SYMBOL_PRINT(Title, Type, Value, Location)
# define YY_STACK_PRINT(Bottom, Top)
# define YY_REDUCE_PRINT(Rule)
#endif /* !Q_PARSER_DEBUG */


/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif


#if YYERROR_VERBOSE

# ifndef yystrlen
#  if defined __GLIBC__ && defined _STRING_H
#   define yystrlen strlen
#  else
/* Return the length of YYSTR.  */
static YYSIZE_T
yystrlen (const char *yystr)
{
  YYSIZE_T yylen;
  for (yylen = 0; yystr[yylen]; yylen++)
    continue;
  return yylen;
}
#  endif
# endif

# ifndef yystpcpy
#  if defined __GLIBC__ && defined _STRING_H && defined _GNU_SOURCE
#   define yystpcpy stpcpy
#  else
/* Copy YYSRC to YYDEST, returning the address of the terminating '\0' in
   YYDEST.  */
static char *
yystpcpy (char *yydest, const char *yysrc)
{
  char *yyd = yydest;
  const char *yys = yysrc;

  while ((*yyd++ = *yys++) != '\0')
    continue;

  return yyd - 1;
}
#  endif
# endif

# ifndef yytnamerr
/* Copy to YYRES the contents of YYSTR after stripping away unnecessary
   quotes and backslashes, so that it's suitable for yyerror.  The
   heuristic is that double-quoting is unnecessary unless the string
   contains an apostrophe, a comma, or backslash (other than
   backslash-backslash).  YYSTR is taken from yytname.  If YYRES is
   null, do not copy; instead, return the length of what the result
   would have been.  */
static YYSIZE_T
yytnamerr (char *yyres, const char *yystr)
{
  if (*yystr == '"')
    {
      YYSIZE_T yyn = 0;
      char const *yyp = yystr;

      for (;;)
        switch (*++yyp)
          {
          case '\'':
          case ',':
            goto do_not_strip_quotes;

          case '\\':
            if (*++yyp != '\\')
              goto do_not_strip_quotes;
            /* Fall through.  */
          default:
            if (yyres)
              yyres[yyn] = *yyp;
            yyn++;
            break;

          case '"':
            if (yyres)
              yyres[yyn] = '\0';
            return yyn;
          }
    do_not_strip_quotes: ;
    }

  if (! yyres)
    return yystrlen (yystr);

  return yystpcpy (yyres, yystr) - yyres;
}
# endif

/* Copy into *YYMSG, which is of size *YYMSG_ALLOC, an error message
   about the unexpected token YYTOKEN for the state stack whose top is
   YYSSP.

   Return 0 if *YYMSG was successfully written.  Return 1 if *YYMSG is
   not large enough to hold the message.  In that case, also set
   *YYMSG_ALLOC to the required number of bytes.  Return 2 if the
   required number of bytes is too large to store.  */
static int
yysyntax_error (YYSIZE_T *yymsg_alloc, char **yymsg,
                yytype_int16 *yyssp, int yytoken)
{
  YYSIZE_T yysize0 = yytnamerr (YY_NULLPTR, yytname[yytoken]);
  YYSIZE_T yysize = yysize0;
  enum { YYERROR_VERBOSE_ARGS_MAXIMUM = 5 };
  /* Internationalized format string. */
  const char *yyformat = YY_NULLPTR;
  /* Arguments of yyformat. */
  char const *yyarg[YYERROR_VERBOSE_ARGS_MAXIMUM];
  /* Number of reported tokens (one for the "unexpected", one per
     "expected"). */
  int yycount = 0;

  /* There are many possibilities here to consider:
     - If this state is a consistent state with a default action, then
       the only way this function was invoked is if the default action
       is an error action.  In that case, don't check for expected
       tokens because there are none.
     - The only way there can be no lookahead present (in yychar) is if
       this state is a consistent state with a default action.  Thus,
       detecting the absence of a lookahead is sufficient to determine
       that there is no unexpected or expected token to report.  In that
       case, just report a simple "syntax error".
     - Don't assume there isn't a lookahead just because this state is a
       consistent state with a default action.  There might have been a
       previous inconsistent state, consistent state with a non-default
       action, or user semantic action that manipulated yychar.
     - Of course, the expected token list depends on states to have
       correct lookahead information, and it depends on the parser not
       to perform extra reductions after fetching a lookahead from the
       scanner and before detecting a syntax error.  Thus, state merging
       (from LALR or IELR) and default reductions corrupt the expected
       token list.  However, the list is correct for canonical LR with
       one exception: it will still contain any token that will not be
       accepted due to an error action in a later state.
  */
  if (yytoken != YYEMPTY)
    {
      int yyn = yypact[*yyssp];
      yyarg[yycount++] = yytname[yytoken];
      if (!yypact_value_is_default (yyn))
        {
          /* Start YYX at -YYN if negative to avoid negative indexes in
             YYCHECK.  In other words, skip the first -YYN actions for
             this state because they are default actions.  */
          int yyxbegin = yyn < 0 ? -yyn : 0;
          /* Stay within bounds of both yycheck and yytname.  */
          int yychecklim = YYLAST - yyn + 1;
          int yyxend = yychecklim < YYNTOKENS ? yychecklim : YYNTOKENS;
          int yyx;

          for (yyx = yyxbegin; yyx < yyxend; ++yyx)
            if (yycheck[yyx + yyn] == yyx && yyx != YYTERROR
                && !yytable_value_is_error (yytable[yyx + yyn]))
              {
                if (yycount == YYERROR_VERBOSE_ARGS_MAXIMUM)
                  {
                    yycount = 1;
                    yysize = yysize0;
                    break;
                  }
                yyarg[yycount++] = yytname[yyx];
                {
                  YYSIZE_T yysize1 = yysize + yytnamerr (YY_NULLPTR, yytname[yyx]);
                  if (! (yysize <= yysize1
                         && yysize1 <= YYSTACK_ALLOC_MAXIMUM))
                    return 2;
                  yysize = yysize1;
                }
              }
        }
    }

  switch (yycount)
    {
# define YYCASE_(N, S)                      \
      case N:                               \
        yyformat = S;                       \
      break
      YYCASE_(0, YY_("syntax error"));
      YYCASE_(1, YY_("syntax error, unexpected %s"));
      YYCASE_(2, YY_("syntax error, unexpected %s, expecting %s"));
      YYCASE_(3, YY_("syntax error, unexpected %s, expecting %s or %s"));
      YYCASE_(4, YY_("syntax error, unexpected %s, expecting %s or %s or %s"));
      YYCASE_(5, YY_("syntax error, unexpected %s, expecting %s or %s or %s or %s"));
# undef YYCASE_
    }

  {
    YYSIZE_T yysize1 = yysize + yystrlen (yyformat);
    if (! (yysize <= yysize1 && yysize1 <= YYSTACK_ALLOC_MAXIMUM))
      return 2;
    yysize = yysize1;
  }

  if (*yymsg_alloc < yysize)
    {
      *yymsg_alloc = 2 * yysize;
      if (! (yysize <= *yymsg_alloc
             && *yymsg_alloc <= YYSTACK_ALLOC_MAXIMUM))
        *yymsg_alloc = YYSTACK_ALLOC_MAXIMUM;
      return 1;
    }

  /* Avoid sprintf, as that infringes on the user's name space.
     Don't have undefined behavior even if the translation
     produced a string with the wrong number of "%s"s.  */
  {
    char *yyp = *yymsg;
    int yyi = 0;
    while ((*yyp = *yyformat) != '\0')
      if (*yyp == '%' && yyformat[1] == 's' && yyi < yycount)
        {
          yyp += yytnamerr (yyp, yyarg[yyi++]);
          yyformat += 2;
        }
      else
        {
          yyp++;
          yyformat++;
        }
  }
  return 0;
}
#endif /* YYERROR_VERBOSE */

/*-----------------------------------------------.
| Release the memory associated to this symbol.  |
`-----------------------------------------------*/

static void
yydestruct (const char *yymsg, int yytype, YYSTYPE *yyvaluep, yyscan_t scanner, struct q_context *context)
{
  YYUSE (yyvaluep);
  YYUSE (scanner);
  YYUSE (context);
  if (!yymsg)
    yymsg = "Deleting";
  YY_SYMBOL_PRINT (yymsg, yytype, yyvaluep, yylocationp);

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YYUSE (yytype);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}




/*----------.
| yyparse.  |
`----------*/

int
yyparse (yyscan_t scanner, struct q_context *context)
{
/* The lookahead symbol.  */
int yychar;


/* The semantic value of the lookahead symbol.  */
/* Default value used for initialization, for pacifying older GCCs
   or non-GCC compilers.  */
YY_INITIAL_VALUE (static YYSTYPE yyval_default;)
YYSTYPE yylval YY_INITIAL_VALUE (= yyval_default);

    /* Number of syntax errors so far.  */
    int yynerrs;

    int yystate;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus;

    /* The stacks and their tools:
       'yyss': related to states.
       'yyvs': related to semantic values.

       Refer to the stacks through separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */

    /* The state stack.  */
    yytype_int16 yyssa[YYINITDEPTH];
    yytype_int16 *yyss;
    yytype_int16 *yyssp;

    /* The semantic value stack.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs;
    YYSTYPE *yyvsp;

    YYSIZE_T yystacksize;

  int yyn;
  int yyresult;
  /* Lookahead token as an internal (translated) token number.  */
  int yytoken = 0;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;

#if YYERROR_VERBOSE
  /* Buffer for error messages, and its allocated size.  */
  char yymsgbuf[128];
  char *yymsg = yymsgbuf;
  YYSIZE_T yymsg_alloc = sizeof yymsgbuf;
#endif

#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))

  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;

  yyssp = yyss = yyssa;
  yyvsp = yyvs = yyvsa;
  yystacksize = YYINITDEPTH;

  YYDPRINTF ((stderr, "Starting parse\n"));

  yystate = 0;
  yyerrstatus = 0;
  yynerrs = 0;
  yychar = YYEMPTY; /* Cause a token to be read.  */
  goto yysetstate;

/*------------------------------------------------------------.
| yynewstate -- Push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
 yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;

 yysetstate:
  *yyssp = yystate;

  if (yyss + yystacksize - 1 <= yyssp)
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYSIZE_T yysize = yyssp - yyss + 1;

#ifdef yyoverflow
      {
        /* Give user a chance to reallocate the stack.  Use copies of
           these so that the &'s don't force the real ones into
           memory.  */
        YYSTYPE *yyvs1 = yyvs;
        yytype_int16 *yyss1 = yyss;

        /* Each stack pointer address is followed by the size of the
           data in use in that stack, in bytes.  This used to be a
           conditional around just the two extra args, but that might
           be undefined if yyoverflow is a macro.  */
        yyoverflow (YY_("memory exhausted"),
                    &yyss1, yysize * sizeof (*yyssp),
                    &yyvs1, yysize * sizeof (*yyvsp),
                    &yystacksize);

        yyss = yyss1;
        yyvs = yyvs1;
      }
#else /* no yyoverflow */
# ifndef YYSTACK_RELOCATE
      goto yyexhaustedlab;
# else
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
        goto yyexhaustedlab;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
        yystacksize = YYMAXDEPTH;

      {
        yytype_int16 *yyss1 = yyss;
        union yyalloc *yyptr =
          (union yyalloc *) YYSTACK_ALLOC (YYSTACK_BYTES (yystacksize));
        if (! yyptr)
          goto yyexhaustedlab;
        YYSTACK_RELOCATE (yyss_alloc, yyss);
        YYSTACK_RELOCATE (yyvs_alloc, yyvs);
#  undef YYSTACK_RELOCATE
        if (yyss1 != yyssa)
          YYSTACK_FREE (yyss1);
      }
# endif
#endif /* no yyoverflow */

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;

      YYDPRINTF ((stderr, "Stack size increased to %lu\n",
                  (unsigned long int) yystacksize));

      if (yyss + yystacksize - 1 <= yyssp)
        YYABORT;
    }

  YYDPRINTF ((stderr, "Entering state %d\n", yystate));

  if (yystate == YYFINAL)
    YYACCEPT;

  goto yybackup;

/*-----------.
| yybackup.  |
`-----------*/
yybackup:

  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */

  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yypact_value_is_default (yyn))
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* YYCHAR is either YYEMPTY or YYEOF or a valid lookahead symbol.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token: "));
      yychar = yylex (&yylval, scanner, context);
    }

  if (yychar <= YYEOF)
    {
      yychar = yytoken = YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }

  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yytable_value_is_error (yyn))
        goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);

  /* Discard the shifted token.  */
  yychar = YYEMPTY;

  yystate = yyn;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END

  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- Do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     '$$ = $1'.

     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];


  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
        case 3:
#line 119 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { context->expr = F1(Q_EXPR_PROGRAM,(yyvsp[0].Expr)); }
#line 1416 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 4:
#line 124 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = (yyvsp[0].Expr); }
#line 1422 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 5:
#line 126 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = (yyvsp[0].Expr); }
#line 1428 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 6:
#line 137 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = F3(Q_EXPR_SELECT,(yyvsp[-2].Expr),(yyvsp[-1].Expr),(yyvsp[0].Expr)); }
#line 1434 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 7:
#line 139 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = F3(Q_EXPR_SELECTDISTINCT,(yyvsp[-2].Expr),(yyvsp[-1].Expr),(yyvsp[0].Expr)); }
#line 1440 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 8:
#line 144 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = L0(Q_EXPR_PROJECTION); }
#line 1446 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 9:
#line 146 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = F1(Q_EXPR_PROJECTION,(yyvsp[0].Expr)); }
#line 1452 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 10:
#line 148 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = L1(Q_EXPR_PROJECTION,(yyvsp[0].List)); }
#line 1458 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 11:
#line 150 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = F1(Q_EXPR_PROJECTION,(yyvsp[0].Expr)); }
#line 1464 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 12:
#line 155 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = L2(Q_EXPR_CLASS,q_newFnc(Q_EXPR_SCOPEDNAME,(yyvsp[-3].List)),(yyvsp[-1].List)); }
#line 1470 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 13:
#line 160 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.List) = List1((yyvsp[0].Expr)); }
#line 1476 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 14:
#line 162 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.List) = q_append((yyvsp[-2].List),(yyvsp[0].Expr)); }
#line 1482 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 15:
#line 167 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = F2(Q_EXPR_BIND,(yyvsp[0].Expr),(yyvsp[-2].Expr)); }
#line 1488 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 16:
#line 169 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = F2(Q_EXPR_BIND,(yyvsp[-2].Expr),(yyvsp[0].Expr)); }
#line 1494 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 17:
#line 171 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = (yyvsp[0].Expr); }
#line 1500 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 18:
#line 182 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = F1(Q_EXPR_FROM,(yyvsp[0].Expr)); }
#line 1506 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 19:
#line 187 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = (yyvsp[0].Expr); }
#line 1512 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 20:
#line 189 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = F2(Q_EXPR_JOIN,(yyvsp[-2].Expr),(yyvsp[0].Expr)); }
#line 1518 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 21:
#line 199 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = L0(Q_EXPR_WHERE); }
#line 1524 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 22:
#line 201 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = F1(Q_EXPR_WHERE,(yyvsp[0].Expr)); }
#line 1530 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 23:
#line 212 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = (yyvsp[0].Expr); }
#line 1536 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 24:
#line 227 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = (yyvsp[0].Expr); }
#line 1542 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 25:
#line 229 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = F2(Q_EXPR_OR,(yyvsp[-2].Expr),(yyvsp[0].Expr)); }
#line 1548 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 26:
#line 242 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = (yyvsp[0].Expr); }
#line 1554 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 27:
#line 244 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = F2(Q_EXPR_AND,(yyvsp[-2].Expr),(yyvsp[0].Expr)); }
#line 1560 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 28:
#line 249 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = (yyvsp[0].Expr); }
#line 1566 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 29:
#line 251 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = F1(Q_EXPR_NOT,(yyvsp[0].Expr)); }
#line 1572 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 30:
#line 262 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = (yyvsp[0].Expr); }
#line 1578 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 31:
#line 264 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = F2((yyvsp[-1].Tag),(yyvsp[-2].Expr),(yyvsp[0].Expr)); }
#line 1584 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 32:
#line 266 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = F2(Q_EXPR_LIKE,(yyvsp[-2].Expr),(yyvsp[0].Expr)); }
#line 1590 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 33:
#line 268 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = (yyvsp[-1].Expr); }
#line 1596 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 34:
#line 273 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = (yyvsp[0].Expr); }
#line 1602 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 35:
#line 275 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = F2((yyvsp[-1].Tag),(yyvsp[-2].Expr),(yyvsp[0].Expr)); }
#line 1608 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 36:
#line 277 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = F2(Q_EXPR_AND,F2(Q_EXPR_GE,(yyvsp[-4].Expr),(yyvsp[-2].Expr)),F2(Q_EXPR_LE,q_newId(q_getId((yyvsp[-4].Expr))),(yyvsp[0].Expr))); }
#line 1614 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 37:
#line 279 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = F2(Q_EXPR_OR,F2(Q_EXPR_LT,(yyvsp[-5].Expr),(yyvsp[-2].Expr)),F2(Q_EXPR_GT,q_newId(q_getId((yyvsp[-5].Expr))),(yyvsp[0].Expr))); }
#line 1620 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 38:
#line 284 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = (yyvsp[0].Expr); }
#line 1626 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 39:
#line 286 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = L2(Q_EXPR_PROPERTY,(yyvsp[-1].Expr),(yyvsp[0].List)); }
#line 1632 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 40:
#line 288 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = (yyvsp[0].Expr); }
#line 1638 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 41:
#line 290 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = q_newFnc(Q_EXPR_SCOPEDNAME,(yyvsp[0].List)); }
#line 1644 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 42:
#line 295 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.List) = List1((yyvsp[0].Expr)); }
#line 1650 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 43:
#line 297 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.List) = q_append((yyvsp[-2].List),(yyvsp[0].Expr)); }
#line 1656 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 46:
#line 307 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = q_newId((yyvsp[0].String));
          /* frees dynamically malloced variable length string value
             allocated by the lexical scanner.
          */
          free((yyvsp[0].String));
        }
#line 1667 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 47:
#line 317 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.List) = List1(q_newId((yyvsp[0].String)));
          /* frees dynamically malloced variable length string value
             allocated by the lexical scanner.
          */
          free((yyvsp[0].String));
        }
#line 1678 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 48:
#line 324 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.List) = List1(q_newId((yyvsp[0].String)));
          /* frees dynamically malloced variable length string value
             allocated by the lexical scanner.
          */
          free((yyvsp[0].String));
        }
#line 1689 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 49:
#line 331 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.List) = q_append((yyvsp[-2].List),q_newId((yyvsp[0].String)));
          /* frees dynamically malloced variable length string value
             allocated by the lexical scanner.
          */
          free((yyvsp[0].String));
        }
#line 1700 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 50:
#line 341 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Tag) = Q_EXPR_EQ; }
#line 1706 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 51:
#line 343 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Tag) = Q_EXPR_NE; }
#line 1712 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 52:
#line 348 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Tag) = Q_EXPR_LT; }
#line 1718 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 53:
#line 350 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Tag) = Q_EXPR_LE; }
#line 1724 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 54:
#line 352 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Tag) = Q_EXPR_GT; }
#line 1730 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 55:
#line 354 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Tag) = Q_EXPR_GE; }
#line 1736 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 56:
#line 359 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = q_newInt((yyvsp[0].Integer)); }
#line 1742 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 57:
#line 361 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = q_newUInt((yyvsp[0].UInteger)); }
#line 1748 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 58:
#line 363 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = q_newDbl((yyvsp[0].Float)); }
#line 1754 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 59:
#line 365 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = q_newChr((yyvsp[0].Char)); }
#line 1760 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 60:
#line 367 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = q_newStr((yyvsp[0].String));
          /* frees dynamically malloced variable length string value
             allocated by the lexical scanner.
          */
          free((yyvsp[0].String));
        }
#line 1771 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 61:
#line 374 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = q_newVar((yyvsp[0].UInteger));
          dollar_warning();
        }
#line 1779 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 62:
#line 378 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = q_newVar((yyvsp[0].UInteger)); }
#line 1785 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 63:
#line 380 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = q_newInt(TRUE); }
#line 1791 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 64:
#line 382 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = q_newInt(FALSE); }
#line 1797 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 65:
#line 384 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = NULL; }
#line 1803 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;

  case 66:
#line 386 "./src/database/database/code/q_parser.y" /* yacc.c:1646  */
    { (yyval.Expr) = NULL; }
#line 1809 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
    break;


#line 1813 "./src/database/database/code/q_parser.c" /* yacc.c:1646  */
      default: break;
    }
  /* User semantic actions sometimes alter yychar, and that requires
     that yytoken be updated with the new translation.  We take the
     approach of translating immediately before every use of yytoken.
     One alternative is translating here after every semantic action,
     but that translation would be missed if the semantic action invokes
     YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
     if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
     incorrect destructor might then be invoked immediately.  In the
     case of YYERROR or YYBACKUP, subsequent parser actions might lead
     to an incorrect destructor call or verbose syntax error message
     before the lookahead is translated.  */
  YY_SYMBOL_PRINT ("-> $$ =", yyr1[yyn], &yyval, &yyloc);

  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);

  *++yyvsp = yyval;

  /* Now 'shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTOKENS] + *yyssp;
  if (0 <= yystate && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTOKENS];

  goto yynewstate;


/*--------------------------------------.
| yyerrlab -- here on detecting error.  |
`--------------------------------------*/
yyerrlab:
  /* Make sure we have latest lookahead translation.  See comments at
     user semantic actions for why this is necessary.  */
  yytoken = yychar == YYEMPTY ? YYEMPTY : YYTRANSLATE (yychar);

  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
#if ! YYERROR_VERBOSE
      yyerror (scanner, context, YY_("syntax error"));
#else
# define YYSYNTAX_ERROR yysyntax_error (&yymsg_alloc, &yymsg, \
                                        yyssp, yytoken)
      {
        char const *yymsgp = YY_("syntax error");
        int yysyntax_error_status;
        yysyntax_error_status = YYSYNTAX_ERROR;
        if (yysyntax_error_status == 0)
          yymsgp = yymsg;
        else if (yysyntax_error_status == 1)
          {
            if (yymsg != yymsgbuf)
              YYSTACK_FREE (yymsg);
            yymsg = (char *) YYSTACK_ALLOC (yymsg_alloc);
            if (!yymsg)
              {
                yymsg = yymsgbuf;
                yymsg_alloc = sizeof yymsgbuf;
                yysyntax_error_status = 2;
              }
            else
              {
                yysyntax_error_status = YYSYNTAX_ERROR;
                yymsgp = yymsg;
              }
          }
        yyerror (scanner, context, yymsgp);
        if (yysyntax_error_status == 2)
          goto yyexhaustedlab;
      }
# undef YYSYNTAX_ERROR
#endif
    }



  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */

      if (yychar <= YYEOF)
        {
          /* Return failure if at end of input.  */
          if (yychar == YYEOF)
            YYABORT;
        }
      else
        {
          yydestruct ("Error: discarding",
                      yytoken, &yylval, scanner, context);
          yychar = YYEMPTY;
        }
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;


/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:

  /* Pacify compilers like GCC when the user code never invokes
     YYERROR and the label yyerrorlab therefore never appears in user
     code.  */
  if (/*CONSTCOND*/ 0)
     goto yyerrorlab;

  /* Do not reclaim the symbols of the rule whose action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;


/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;      /* Each real token shifted decrements this.  */

  for (;;)
    {
      yyn = yypact[yystate];
      if (!yypact_value_is_default (yyn))
        {
          yyn += YYTERROR;
          if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYTERROR)
            {
              yyn = yytable[yyn];
              if (0 < yyn)
                break;
            }
        }

      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
        YYABORT;


      yydestruct ("Error: popping",
                  yystos[yystate], yyvsp, scanner, context);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END


  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", yystos[yyn], yyvsp, yylsp);

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturn;

/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturn;

#if !defined yyoverflow || YYERROR_VERBOSE
/*-------------------------------------------------.
| yyexhaustedlab -- memory exhaustion comes here.  |
`-------------------------------------------------*/
yyexhaustedlab:
  yyerror (scanner, context, YY_("memory exhausted"));
  yyresult = 2;
  /* Fall through.  */
#endif

yyreturn:
  if (yychar != YYEMPTY)
    {
      /* Make sure we have latest lookahead translation.  See comments at
         user semantic actions for why this is necessary.  */
      yytoken = YYTRANSLATE (yychar);
      yydestruct ("Cleanup: discarding lookahead",
                  yytoken, &yylval, scanner, context);
    }
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
                  yystos[*yyssp], yyvsp, scanner, context);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif
#if YYERROR_VERBOSE
  if (yymsg != yymsgbuf)
    YYSTACK_FREE (yymsg);
#endif
  return yyresult;
}
#line 389 "./src/database/database/code/q_parser.y" /* yacc.c:1906  */


#define YY_NO_UNPUT
#define YY_NO_INPUT

#include "q_parser.h" /* generated by flex */


int
yyerror(
    yyscan_t yyscanner, struct q_context *context, char *text)
{
    OS_UNUSED_ARG(yyscanner);

    OS_REPORT(OS_ERROR,"SQL parse failed",0,"%s near line: %d, column: %d",
              text, context->line, context->column);

    return 0;
}

void
dollar_warning(
    void)
{
    OS_REPORT(OS_WARNING,"SQL parser",0,"The use of '$' is deprecated, use '%%' instead");
}

q_expr
q_parse(
    const c_char *expression)
{
    YY_BUFFER_STATE buffer;
    yyscan_t scanner;
    struct q_context context = { 1, 0, NULL };
    q_expr e = NULL;

    if (expression) {
        q_parser_lex_init(&scanner);
        buffer = q_parser__scan_string(expression, scanner);
        if (yyparse(scanner, &context) == 0) {
            e = context.expr;
            q_exprSetText(e, expression);
        } else {
            /* 1 on invalid input, 2 on memory exhaustion */
            q_dispose(context.expr);
            context.expr = NULL;
        }

        q_parser__delete_buffer(buffer, scanner);
        q_parser_lex_destroy(scanner);
    }

    return e;
}
